sudo: required
services:
  - docker
dist: trusty
language: rust
rust:
  - nightly
cache:
  - docker
before_install:
  - docker pull edattore/titan-image
jobs:
  include:
  - stage: unit-tests
    script: docker run -d edattore/titan-image /bin/bash -c "cd titan-web-client && yarn && yarn test"
  - stage: unit-tests
    script: docker run -d edattore/titan-image /bin/bash -c "cd titan-server && cargo test"
  - stage: deploy-staging
    script: skip
