[development]
address = "127.0.0.1"
auth_key = "dummy_key"
avatar_base_url = "https://clanunknownsoldiers.com/wcf/images/avatars"

[development.databases.unkso_main_forums]
url = "mysql://root@localhost/unkso_main_forums"

[development.databases.titan_primary]
url = "mysql://root@localhost/titan_primary"
