export enum ActionType {
    // Authentication
    AUTH_SESSION_LOGIN,
    AUTH_SESSION_LOGOUT,

    // File entries
    FILE_ENTRIES_SET_TYPES,

    // User profile
    PROFILE_SET_USER,
    PROFILE_SET_FILE_ENTRIES,
    PROFILE_ADD_FILE_ENTRY,
    PROFILE_SET_EXCUSES,
    PROFILE_ADD_EXCUSE,
    PROFILE_CLEAR_USER,

    // Organization
    ORGANIZATION_ADD_MEMBER,
    ORGANIZATION_REMOVE_MEMBER,
    ORGANIZATION_SET_DETAILS,
    ORGANIZATION_SET_CHILDREN,
    ORGANIZATION_SET_COC,
    ORGANIZATION_SET_REPORTS,
    ORGANIZATION_SET_MEMBERS,
    ORGANIZATION_SET_ROLES,
    ORGANIZATION_CLEAR,
}
