export const AUTH_SESSION_LOGIN = 'AUTH_SESSION_LOGIN';
export const AUTH_SESSION_LOGOUT = 'AUTH_SESSION_LOGOUT';

export const PROFILE_SET_USER = 'PROFILE_SET_USER';
export const PROFILE_SET_FILE_ENTRIES = 'PROFILE_SET_FILE_ENTRIES';
