export const AUTH_SESSION_LOGIN = 'AUTH_SESSION_LOGIN';
export const AUTH_SESSION_LOGOUT = 'AUTH_SESSION_LOGOUT';

export const FILE_ENTRIES_SET_TYPES = 'FILE_ENTRIES_SET_TYPES';

export const PROFILE_SET_USER = 'PROFILE_SET_USER';
export const PROFILE_SET_FILE_ENTRIES = 'PROFILE_SET_FILE_ENTRIES';
export const PROFILE_ADD_FILE_ENTRY = 'PROFILE_ADD_FILE_ENTRY';
export const PROFILE_SET_EXCUSES = 'PROFILE_SET_EXCUSES';
export const PROFILE_ADD_EXCUSE = 'PROFILE_ADD_EXCUSE';
export const PROFILE_CLEAR_USER = 'PROFILE_CLEAR_USER';
