#[derive(Serialize, Deserialize, Queryable)]
pub struct WcfUser {
    pub user_id: i32,
    pub username: String,
    pub email: String,
    pub password: String,
    pub access_token: String,
    pub language_id: i32,
    pub registration_date: i32,
    pub style_id: i32,
    pub banned: bool,
    pub ban_reason: Option<String>,
    pub ban_expires: i32,
    pub activation_code: i32,
    pub last_lost_password_request_time: i32,
    pub lost_password_key: String,
    pub last_username_change: i32,
    // pub newEmail: String,
    // pub oldUsername: String,
    // pub quitStarted: i32,
    // pub reactivationCode: i32,
    // pub registrationIpAddress: String,
    // pub avatarID: Option<i32>,
    // pub disableAvatar: bool,
    // pub disableAvatarReason: Option<String>,
    // pub disableAvatarExpires: i32,
    // pub enableGravatar: bool,
    // pub gravatarFileExtension: String,
    // pub signature: Option<String>,
    // pub signatureEnableBBCodes: bool,
    // pub signatureEnableHtml: bool,
    // pub signatureEnableSmilies: bool,
    // pub disableSignature: bool,
    // pub disableSignatureReason: Option<String>,
    // pub disableSignatureExpires: i32,
    // pub lastActivityTime: i32,
    // pub profileHits: i32,
    // pub rankID: Option<i32>,
    // pub userTitle: String,
    // pub userOnlineGroupID: Option<i32>,
    // pub activityPoints: i32,
    // pub notificationMailToken: String,
    // pub authData: String,
    // pub likesReceived: i32,
    // pub socialNetworkPrivacySettings: Option<String>,
    // pub wbbPosts: i32
}
