table! {
    wcf1_user (userID) {
        userID -> Integer,
        username -> Varchar,
        email -> Varchar,
        password -> Varchar,
        accessToken -> Varchar,
        languageID -> Integer,
        registrationDate -> Integer,
        styleID -> Integer,
        banned -> Bool,
        banReason -> Nullable<Mediumtext>,
        banExpires -> Integer,
        activationCode -> Integer,
        lastLostPasswordRequestTime -> Integer,
        lostPasswordKey -> Varchar,
        lastUsernameChange -> Integer,
        // newEmail -> Varchar,
        // oldUsername -> Varchar,
        // quitStarted -> Integer,
        // reactivationCode -> Integer,
        // registrationIpAddress -> Varchar,
        // avatarID -> Nullable<Integer>,
        // disableAvatar -> Bool,
        // disableAvatarReason -> Nullable<Text>,
        // disableAvatarExpires -> Integer,
        // enableGravatar -> Bool,
        // gravatarFileExtension -> Varchar,
        // signature -> Nullable<Text>,
        // signatureEnableBBCodes -> Bool,
        // signatureEnableHtml -> Bool,
        // signatureEnableSmilies -> Bool,
        // disableSignature -> Bool,
        // disableSignatureReason -> Nullable<Text>,
        // disableSignatureExpires -> Integer,
        // lastActivityTime -> Integer,
        // profileHits -> Integer,
        // rankID -> Nullable<Integer>,
        // userTitle -> Varchar,
        // userOnlineGroupID -> Nullable<Integer>,
        // activityPoints -> Integer,
        // notificationMailToken -> Varchar,
        // authData -> Varchar,
        // likesReceived -> Integer,
        // socialNetworkPrivacySettings -> Nullable<Text>,
        // wbbPosts -> Integer,
    }
}
